### PR TITLE
MODINVSTOR-537: Release mod-inventory-storage 19.2.5

### PR DESCRIPTION
**Pull request by julianladisch**
* Search queries without database index (MODINVSTOR-472)
* Add Index for Instances Full-text Subjects Search (MODINVSTOR-499)
* RMB 30.2.4: totalRecords for limit=0, requestId logging (MODINVSTOR-532, RMB-673, RMB-670)

### CODE REVIEW

**Comment by julianladisch** [comment]
No, I did not push the tag because it is not clear whether all agree that 19.2.5 should contain exactly the issues I've picked.

**Comment by julianladisch** [comment]
This can be closed if master is released as 20.0.0 or 19.3.0 for Q2 2020 as discussed on https://issues.folio.org/browse/MODINVSTOR-536 because this pull request contains only cherry-picked commits from master.

**Comment by marcjohnson-kint** [comment]
Thanks @julianladisch 

I think I misinterpreted how far this branch had got towards releasing, thank you for clarifying that.

I agree, either this can be used as a basis for consolidating all of the changes to a 19.2.5 release or (my preference) it be closed when 20.0.0 is released.

**Comment by julianladisch** [comment]
Closed because all has been released as 19.3.0.

**Pull request closed without merging**
