### PR TITLE
MODINVSTOR-215: Use sort or search index depending on the result size.

### PR DESCRIPTION
**Pull request by julianladisch**

### CODE REVIEW

**Comment by julianladisch** [comment]
@adamdickmeiss You wrote:
> re-parses of SQL. Why not have an SQL query object
Can you elaborate?

**Comment by adamdickmeiss** [comment]
Thx. I can see in this case it's broken parsing of CQL. Using regular expressions lookup or string lookup's such as query.contains("holdingsRecords.") or try to inspect sorting is just plain broken and will lead to all kinds of bad things when some day people do use those names as terms.. Example: https://github.com/folio-org/mod-codex-mux/blob/master/src/main/java/org/folio/codex/Multiplexer.java#L347

**Comment by julianladisch** [comment]
> query.contains("holdingsRecords.")

This is not part of this pull request.

**Comment by adamdickmeiss** [comment]
> > query.contains("holdingsRecords.")
> 
> This is not part of this pull request.

Indeed. But it is the style that is used, so I understand why that way of "accessing" CQL is used.

**Pull request merged**
