### PR TITLE
Shelflocations merge master

### PR DESCRIPTION
**Pull request by kurtnordstrom**

### CODE REVIEW

**Comment by dcrossleyau** [comment]
I did a light review: Verified the ramls with raml-cop, and built the project. Did not conduct Marc's other tests.

While comparing shelf-location.raml with item-storage.raml i discovered how to solve the inconsistency with the [configuration advice](https://github.com/folio-org/raml-module-builder/blob/master/README.md#step-6-design-the-raml-files) for "schema key name" of collections. Thanks. I will add a separate issue ticket for this.

**Comment by marcjohnson-kint** [comment]
Thanks @dcrossleyau please add me as a watcher to that issue regarding the schema references in collections

**Comment by dcrossleyau** [comment]
@marcjohnson-kint and @kurtnordstrom:

Added [FOLIO-912](https://issues.folio.org/browse/FOLIO-912) to clarify the advice for configuration of schema collections.

Note that this PR has configuration such that the resulting Java class name is "ShelflocationsJson" rather than "Shelflocations".

**Comment by marcjohnson-kint** [comment]
@dcrossleyau Thanks for spotting this, I've fixed it (https://github.com/folio-org/mod-inventory-storage/pull/20/commits/c139f567e893a80c9ad4c045af6f09cc50ec7204) and re-tested.

**Pull request merged**
