### PR TITLE
MODINVSTOR-977: hasRemoveEvent fixing sporadic unit test failures

### PR DESCRIPTION
**Pull request by julianladisch**
About 30% of all builds fail because of at least one of these failures:

```
InstanceStorageTest.canDeleteInstancesByCql:487
  Expected: is "DELETE"
       but: was "CREATE"
```

```
  HoldingsStorageTest.canDeleteHoldingsByCql:647
Expected: is "DELETE"
     but: was "CREATE"
```

```
ItemStorageTest.canDeleteItemsByCql:2045
  Expected: is "DELETE"
       but: was "CREATE"
```

The current tests assert that the last event is the expected DELETE event. Due to the async nature of Kafka messages there might be a CREATE event.

Rewrite the test so that it succeeds if the expected DELETE event exists at any position in the event stream.

Write a hasRemoveEvent method that can be used with await().until(() -> hasRemoveEvent(...));

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
Thank you for investigating the test failures.

I think this has raised my awareness of how unstable these tests are (I don't really understand why they have got significantly more unstable recently).

With that in mind, whilst I think there could be a need for a more general overhaul of these aspects of the tests (e.g. to clear out any messages before the assertion / check part of the test and to use matchers rather than avoiding assertion exceptions), I'm in favour of merging this in case it improves upon the current situation.

**Review by marcjohnson-kint — APPROVED** [review]

**Review by adamdickmeiss — COMMENTED** [review]
I prefer to use FakeKafkaConsumer.removeAllEvents() before the test begins, so that only events  from *this* tests are seen.

Other than that, before MODINVSTOR-976 should be fixed first.

**Comment by marcjohnson-kint** [comment]
> I prefer to use FakeKafkaConsumer.removeAllEvents() before the test begins, so that only events from _this_ tests are seen.

I agree. Sometimes I also want to remove the events before the important act in the test. Some of the steps to prepare the initial state for a test can also publish events and those can get in the way as well.

**Comment by adamdickmeiss** [comment]
Calling FakeKafkaConsumer.removeAllEvents() does not fix the ItemStorageTest case, so I think we should go with the solution here.

**Review by adamdickmeiss — APPROVED** [review]

**Pull request merged**
