### PR TITLE
MODDPUBSUB-181: Update folio-kafka-wrapper version to 2.3.1

### PR DESCRIPTION
**Pull request by VRohach**

### CODE REVIEW

**Review by RuslanLavrov — APPROVED** [review]

**Review by Aliaksandr-Fedasiuk — APPROVED** [review]

**Review by KaterynaSenchenko — APPROVED** [review]

**Comment by marcjohnson-kint** [comment]
@KaterynaSenchenko I thought you said on the issue that mod-inventory-storage was unaffected by this change because it used a different mechanism?

**Comment by KaterynaSenchenko** [comment]
@marcjohnson-kint, that's right - and there won't be a hot fix for mod-inventory-storage. I just thought that the folio-kafka-wrapper SNAPSHOT version was already set in master and this PR sets it to the latest release version. Anyway, it won't hurt to have latest folio-kafka-wrapper dependency in master branch, if that's OK with you of course

**Comment by marcjohnson-kint** [comment]
> @marcjohnson-kint, that's right - and there won't be a hot fix for mod-inventory-storage. I just thought that the folio-kafka-wrapper SNAPSHOT version was already set in master and this PR sets it to the latest release version. Anyway, it won't hurt to have latest folio-kafka-wrapper dependency in master branch, if that's OK with you of course

Thanks for explaining that, it helps me understand.

That is more than ok with me. I much prefer the mainline to use release artefacts.

**Comment by KaterynaSenchenko** [comment]
Thank you, @marcjohnson-kint! Could you approve this PR so that we could merge it?

**Review by julianladisch — APPROVED** [review]

**Pull request merged**
