### PR TITLE
Add identifierTypeObject virtual field into instance.json

### PR DESCRIPTION
**Pull request by MikeTaylor**
Fixes MODGQL-123.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
@adamdickmeiss Is RMB now running in sufficiently deterministic a way that I can be confident these passed tests means my schema change is OK?

**Comment by julianladisch** [comment]
RMB has a deterministic sort order fix for GenerateRunner:
https://github.com/folio-org/raml-module-builder/pull/628
This hasn't been released yet, though.

Using javaType should be sufficient to prevent a name clash.

**Comment by MikeTaylor** [comment]
@julianladisch I know I have the option of forcing the issue with `javaType`, but I don't want to introduce that if it's not needed in this case. So what I really want at the moment is just for RMB to reliably tell me whether or not it _is_ needed.

**Comment by MikeTaylor** [comment]
I am going to interpret the radio silence as agreement that this is good to merge. If the merge _does_ cause problems, that can be taken as an incentive to get https://github.com/folio-org/raml-module-builder/pull/628 deployed soonest, to prevent a recurrence!

**Pull request merged**
