### PR TITLE
[BUGFIX]: MODINVSTOR-367: Maintain item status date even if item record is edited

### PR DESCRIPTION
**Pull request by VRohach**
Bugfix regarding item status date at the "item" object:
Time Zone didn't exist in this field.

### CODE REVIEW

**Comment by bohdan-suprun** [comment]
@VRohach, let's wait a reply on https://github.com/folio-org/mod-inventory-storage/pull/361.

**Comment by VRohach** [comment]
> @VRohach, let's wait a reply on #361.

Sure.

**Comment by marcjohnson-kint** [comment]
What is the difference between this change and #361 ?

**Comment by VRohach** [comment]
> What is the difference between this change and #361 ?

So, this PR is for the item status date. (In object "item" situated "status" object. In it, there is "date" field). But https://github.com/folio-org/mod-inventory-storage/pull/361 implemented for the instance status date. 

So, the approach is the same, but for other functionalities.

**Comment by bohdan-suprun** [comment]
Hi @marcjohnson-kint, it is similar changes to #361, except for a different property. 

I think it is ready to be merged, unless you have any objection.

**Comment by marcjohnson-kint** [comment]
> Hi @marcjohnson-kint, it is similar changes to #361, except for a different property.
> 
> I think it is ready to be merged, unless you have any objection.

No objection, I deleted my comment asking about the difference. Feel free to approve.

**Pull request merged**
