### PR TITLE
Add `illPolicy` link-field annotation for mod-graphql

### PR DESCRIPTION
**Pull request by MikeTaylor**
Needed for ReShare issue PR-611.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
@nielserik Can you imagine any sane reason why this would have built in Jenkins after I made the first commit, but not after I made the second?

**Comment by MikeTaylor** [comment]
Or why the *continuous-integration/jenkins/branch* build would fail when the *continuous-integration/jenkins/pr-merge* build succeeds?!

**Comment by MikeTaylor** [comment]
I am going to close and re-open this PR, on the offchange that this was a Jenkins weirdness — though the log does complain about `illPolicy`, which is the structure I added, so I think that is a forlorn hope.

**Comment by MikeTaylor** [comment]
Oh, I see closing and re-opening doesn't help. All right, then I will push a trivial change.

**Comment by MikeTaylor** [comment]
No, same thing: the **continuous-integration/jenkins/branch** build fails but the **continuous-integration/jenkins/pr-merge** build succeeds.

**Comment by bohdan-suprun** [comment]
@MikeTaylor, there is already java class with `IllPolicy` name. You should either rename the new property (e.g. `illPolicyHoldings`) or add `javaType` attribute for the new property, e.g. `"javaType": "org.folio.rest.jaxrs.model.IllPolicyHoldingsRecord"`, so that RAML will generate java class for it with different name.

**Comment by MikeTaylor** [comment]
Thank you @bohdan-suprun, very helpful comments. I'll get on them.

Do you have any idea why the **continuous-integration/jenkins/pr-merge** check is passing?

**Comment by bohdan-suprun** [comment]
> Thank you @bohdan-suprun, very helpful comments. I'll get on them.
> 
> Do you have any idea why the **continuous-integration/jenkins/pr-merge** check is passing?

No, I don't. Looks confusing to me.

**Comment by MikeTaylor** [comment]
@bohdan-suprun Please re-review!

**Pull request merged**
